CREATE TABLE movie
(
    id         BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    title      VARCHAR(255),
    rating     DECIMAL,
    sinopse    VARCHAR(255),
    poster_url VARCHAR(255),
    CONSTRAINT pk_movie PRIMARY KEY (id)
);