INSERT INTO TB_ENTRYY_TAG(HASH_TAG) VALUES ("AEADASDAW213SDA");

INSERT INTO TB_EMPLOYEE(NAME, EMAIL, AGE) VALUES ('Sharon Underwood', 'mauri@email.com', 21);
INSERT INTO TB_EMPLOYEE(NAME, EMAIL, AGE) VALUES ('Yoshio Rivas', 'turpis@email.com', 23);