INSERT INTO TB_PRODUTO(NOME, PRECO, DATA_CADASTRO)
VALUES ('Teclado', 350.00, CURRENT_TIMESTAMP);
INSERT INTO TB_PRODUTO(NOME, PRECO, DATA_CADASTRO)
VALUES ('Mouse', 200.00, CURRENT_TIMESTAMP);
INSERT INTO TB_PRODUTO(NOME, PRECO, DATA_CADASTRO)
VALUES ('Monitor', 1200.00, CURRENT_TIMESTAMP);
INSERT INTO TB_PRODUTO(NOME, PRECO, DATA_CADASTRO)
VALUES ('Headset', 450.00, CURRENT_TIMESTAMP);
INSERT INTO TB_PRODUTO(NOME, PRECO, DATA_CADASTRO)
VALUES ('Webcam HD', 300.00, CURRENT_TIMESTAMP);
