INSERT INTO TB_EMPLOYEE(NAME, EMAIL, AGE ) VALUES   ('Sharon Underwood','mauris.id@icloud.net',8);
INSERT INTO TB_EMPLOYEE(NAME, EMAIL, AGE) VALUES   ('Yoshio Rivas','turpis.nec@icloud.couk',1);

INSERT INTO TB_ENTRY_TAG(HASH_TAG) VALUES ('EWRWERAVFG44455656');
UPDATE TB_EMPLOYEE SET ENTRY_TAG_ID = 1 WHERE ID=2;

