INSERT INTO ESTADIO(ID, NOME, CAPACIDADE)
VALUES (NEXT VALUE FOR ESTADIO_SEQ, 'PACAEMBU', 2000);
INSERT INTO ESTADIO(ID, NOME, CAPACIDADE)
VALUES (NEXT VALUE FOR ESTADIO_SEQ, 'MORUMBI', 4000);
INSERT INTO ESTADIO(ID, NOME, CAPACIDADE)
VALUES (NEXT VALUE FOR ESTADIO_SEQ, 'NEO QUIMICA ARENA', 5000);