INSERT INTO TB_ESTADIO(ID, NOME, CAPACIDADE) VALUES (1, 'PACAEMBU', 2000);
INSERT INTO TB_ESTADIO(ID, NOME, CAPACIDADE) VALUES (2, 'MORUMBI', 4000);
INSERT INTO TB_ESTADIO(ID, NOME, CAPACIDADE) VALUES (3, 'NEO QUIMICA ARENA', 5000);