INSERT INTO TB_ESTADIO(ID,NOME,CAPACIDADE) VALUES (1, 'PACAEMBU', 2000);
INSERT INTO TB_ESTADIO(ID,NOME,CAPACIDADE) VALUES (2, 'MORUMBI', 4000);
INSERT INTO TB_ESTADIO(ID,NOME,CAPACIDADE) VALUES (3, 'NEO QUIMICA ARENA', 5000);

INSERT INTO TB_JOGO (ID, MATA_MATA, ID_ESTADIO) VALUES (NEXT VALUE FOR JOGO_SEQ, 'TIME A VS TIME B', 3);
INSERT INTO TB_JOGO (ID, MATA_MATA, ID_ESTADIO) VALUES (NEXT VALUE FOR JOGO_SEQ, 'TIME B VS TIME C', 3);
INSERT INTO TB_JOGO (ID, MATA_MATA, ID_ESTADIO) VALUES (NEXT VALUE FOR JOGO_SEQ, 'TIME C VS TIME D', 1);

